ANTHROPIC_API_KEY_ENV = "ANTHROPIC_API_KEY"
MODEL = "claude-haiku-4-5-20251001"
SUMMARY_MODEL = "claude-sonnet-4-6"
MAX_INPUT_TOKENS = 4096
MAX_OUTPUT_TOKENS = 500
EXTRACTION_MAX_TOKENS = 500
SUMMARY_MAX_TOKENS = 800
SCREENING_DB_PATH = "data/screening.sqlite3"
