ANTHROPIC_API_KEY_ENV = "ANTHROPIC_API_KEY"
MODEL = "claude-haiku-4-5-20251001"
MAX_INPUT_TOKENS = 4096
MAX_OUTPUT_TOKENS = 500
EXTRACTION_MAX_TOKENS = 500
CANDIDATES_JSONL_PATH = "data/candidates.jsonl"
